services:
  - type: web
    name: receba-bi
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_DISK_PATH
        value: /var/data
    disk:
      name: receba-bi-data
      mountPath: /var/data
      sizeGB: 1
